Development of insert purchase order endpoint of the second requirements
aelmo/bootcamp-meli-frescos pull request #16
Opened 2021-07-05 19:42 UTC by jaijuni

This PR is about the development of second requirement purchase order insert endpoint

2021-07-05 20:59 UTC, aelmo requested changes

2021-07-05 20:59 UTC, aelmo commented on src/main/java/com/mercadolibre/bootcampmelifrescos/controller/PurchaseOrderController.java
> +    @PostMapping("/orders/")
Coloca pelo menos os docs básicos do swagger, mas precisamos melhorá-los depois.

Ex: https://github.com/aelmo/bootcamp-meli-frescos/pull/18

2021-07-05 20:59 UTC, aelmo commented on src/main/java/com/mercadolibre/bootcampmelifrescos/dtos/CartProductsDTO.java
> +    private Integer quantity;
Aqui talvez validar se a quantidade não é negativa?

2021-07-05 20:59 UTC, aelmo commented on src/main/java/com/mercadolibre/bootcampmelifrescos/dtos/request/PurchaseOrderDTO.java
> +    @NotNull(message="The buyer id cannot be null")
```suggestion
    @NotNull(message = "The buyer id cannot be null")
```

2021-07-05 20:59 UTC, aelmo commented on src/main/java/com/mercadolibre/bootcampmelifrescos/dtos/request/PurchaseRequestProductsDTO.java
> +    @NotNull(message = "The product quantity cannot be null")
Aqui você valida se não é null mas em CartDTO não.. algum motivo específico?

2021-07-05 20:59 UTC, aelmo commented on src/main/java/com/mercadolibre/bootcampmelifrescos/repository/BatchRepository.java
> +    @Query(value = "SELECT * FROM batch WHERE batch.product_id = :product_id AND batch.current_quantity > 0 ORDER BY batch.current_quantity DESC LIMIT 1" ,nativeQuery = true)
Precisa realmente dessa query? Não dá pra simplesmente usar o Spring Data/JPA?

2021-07-06 12:20 UTC, jaijuni commented on src/main/java/com/mercadolibre/bootcampmelifrescos/repository/BatchRepository.java
> +    @Query(value = "SELECT * FROM batch WHERE batch.product_id = :product_id AND batch.current_quantity > 0 ORDER BY batch.current_quantity DESC LIMIT 1" ,nativeQuery = true)
eu pelo menos não consegui construir usando JPA, vc teria alguma dica ou lugar pra pesquisar ?

2021-07-06 18:55 UTC, gsennameli commented on src/main/java/com/mercadolibre/bootcampmelifrescos/repository/BatchRepository.java
> +    Batch getBatchByProductId(@Param("product_id") Long productId);
Acho que daria para fazer algo tipo assim e não precisaria do @Query
`Optional<Batch> findByProduct(Product product);`

2021-07-06 18:57 UTC, gsennameli commented on src/main/java/com/mercadolibre/bootcampmelifrescos/repository/BatchRepository.java
> +    Batch getBatchByProductId(@Param("product_id") Long productId);
Acho que daria para fazer algo tipo assim e não precisaria do @Query
```suggestion
    Optional<Batch> findByProduct(Product product);
```

2021-07-07 17:55 UTC, closed without merging